include: package:flutter_lints/flutter.yaml

linter:

  # or a specific dart file by using the `// ignore: name_of_lint` and
  # `// ignore_for_file: name_of_lint` syntax on the line or in the file

  rules:
    avoid_print: true
    prefer_relative_imports: true
